# .github/workflows/publish.yml
name: publish

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # checks out a copy of the repository on the runners machine
      - name: Checkout repository
        uses: actions/checkout@v4
    # Install Java
      - name: Prepare Java
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin
    # Setup leiningen
      - name: Setup Leiningen
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          lein: 2.10.0
    # Setup NPM
      - name: Setup NPM
        uses: actions/setup-node@v6
        with:
          node-version: 22
    # Setup Sass
      - name: Setup Sass
        run: npm install -g sass
    # cache Clojure(java) dependencies
      - name: Cache Java modules
        uses: actions/cache@v4
        env:
          cache-name: cache-java-modules
        with:
          # Maven cache files are stored in `~/.m2` on Linux/macOS
          path: ~/.m2
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/deps.edn', '**/project.clj') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
    # Fetch Lein Deps
      - name: Fetch deps
        run: lein deps
    # Build the blog    
      - name: Build Blog
        run: lein run
    # Deploy to GH-pages
      - name: Deploy Blog
        # uses: peaceiris/actions-gh-pages@v3
        # with: 
        #   github_token: ${{ secrets.GITHUB_TOKEN }}
        #   publish_dir: ./public/
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          commit-message: ${{ github.event.head_commit.message }}
          branch: gh-pages                                
          single-commit: yes
          folder: public/